development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: varsity_tutors_store
  pool: 5
  username: root
  password:
  shost: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: varsity_tutors_store
  pool: 5
  username: root
  password:
  shost: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: varsity_tutors_store
  pool: 5
  username: root
  password:
  shost: localhost
